services:
  crashcaster:
    build: .
    image: crashcaster:latest
    container_name: crashcaster
    environment:
      - PORT=8080
    ports:
      - "8501:8080"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest        # official multi-arch image (works on Apple Silicon)
    container_name: crashcaster-ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    # Print logs to stdout (so docker logs shows the URL) and tunnel to the app
    command: >
      http --log=stdout --log-format=logfmt
      --request-header-add='X-Forwarded-Proto:https'
      http://crashcaster:8080
    ports:
      - "4040:4040"                  # publish ngrok's local API so you can query the URL
    depends_on:
      - crashcaster
    restart: unless-stopped
